#!/usr/bin/env python3
"""Apply all 8 changes to saltus_dw_architecture.html"""

import sys

FILE = r"c:/Users/Adrian Smith/OneDrive - Space01/Documents/Saltus_Architecture/saltus_dw_architecture.html"

with open(FILE, 'r', encoding='utf-8') as f:
    html = f.read()

original_len = len(html)
changes_ok = 0
changes_fail = 0

def apply_change(name, old, new, content):
    global changes_ok, changes_fail
    if old in content:
        result = content.replace(old, new, 1)
        print(f"  OK: {name}")
        changes_ok += 1
        return result
    else:
        print(f"FAIL: {name} — old string not found")
        changes_fail += 1
        return content

# ── Change 1: Add 'datamart' to LC colour map ─────────────────────────────────
OLD1 = "  gold:     '#eab308',\n  consumer: '#22c55e',"
NEW1 = "  gold:     '#eab308',\n  datamart: '#8b5cf6',\n  consumer: '#22c55e',"
html = apply_change("Change 1: Add datamart to LC colour map", OLD1, NEW1, html)

# ── Change 2: Replace 6 Gold nodes ───────────────────────────────────────────
OLD2 = """  client_dim: {
    id:'client_dim', label:'Client Dim', sub:'SCD Type 2', icon:'👥', layer:'gold', azSvc:'synapse',
    desc:'Client dimension with full change history via SCD Type 2, stored in Azure Synapse Analytics Dedicated SQL Pool. Tracks changes to risk profile, adviser assignment and business unit over time.',
    attrs:['client_key','client_id','full_name','risk_profile','business_unit','adviser_key','valid_from','valid_to','is_current'],
    integration:'ADF pipeline runs SCD2 merge into Synapse Dedicated SQL Pool. New rows inserted on any attribute change. Surrogate key generated by Synapse IDENTITY column.',
    freq:'Daily', vol:'~15k current + ~45k historical rows',
    eg:`{
  "client_key": 10001,
  "client_id": "C12345",
  "full_name": "Adrian Smith",
  "risk_profile": "Balanced",
  "valid_from": "2023-06-01",
  "valid_to": "9999-12-31",
  "is_current": true
}`,
  },
  account_dim: {
    id:'account_dim', label:'Account Dim', sub:'SCD Type 2', icon:'📁', layer:'gold', azSvc:'synapse',
    desc:'Account dimension tracking plan type changes, status transitions and custodian assignments, stored in Azure Synapse Dedicated SQL Pool with full SCD Type 2 history.',
    attrs:['account_key','account_id','client_key','plan_type','status','custodian_number','valid_from','valid_to','is_current'],
    integration:'ADF SCD2 merge into Synapse Dedicated SQL Pool. Distribution key on account_id for query performance. Custodian number changes trigger a new version row.',
    freq:'Daily', vol:'~40k current + ~120k historical rows',
    eg:`{
  "account_key": 20001,
  "account_id": "ACC001",
  "plan_type": "ISA",
  "status": "Active",
  "custodian_number": "CUST99",
  "valid_from": "2022-04-06",
  "is_current": true
}`,
  },
  adviser_dim: {
    id:'adviser_dim', label:'Adviser Dim', sub:'SCD Type 2', icon:'\U0001f9d1\u200d\U0001f4bc', layer:'gold', azSvc:'synapse',
    desc:'Adviser dimension in Azure Synapse Dedicated SQL Pool. Built from activity data and CURO adviser records. Tracks business unit moves and role changes via SCD Type 2.',
    attrs:['adviser_key','adviser_id','full_name','business_unit','qualification_level','valid_from','valid_to','is_current'],
    integration:'ADF pipeline merges Silver activity adviser list with CURO adviser master. Loaded into Synapse Dedicated SQL Pool via PolyBase/COPY INTO from ADLS Gen2 staging.',
    freq:'Daily', vol:'~250 advisers',
    eg:`{
  "adviser_key": 30001,
  "adviser_id": "A789",
  "full_name": "James Wilson",
  "business_unit": "RB",
  "qualification": "Level 4",
  "is_current": true
}`,
  },
  time_dim: {
    id:'time_dim', label:'Time Dim', sub:'Date Spine', icon:'\U0001f4c5', layer:'gold', azSvc:'synapse',
    desc:'Date spine covering 2010\u20132035 in Azure Synapse Dedicated SQL Pool. Business day flags, FCA reporting periods and UK public holiday markers. Replicated across all Synapse distributions.',
    attrs:['date_key','date','day_of_week','week','month','quarter','year','is_business_day','is_month_end','fca_period'],
    integration:'Static table loaded via COPY INTO from ADLS Gen2. REPLICATE distribution for optimal join performance. Refreshed annually to extend forward dates.',
    freq:'Annual refresh', vol:'~9,000 rows (25-year span)',
    eg:`{
  "date_key": 20240115,
  "date": "2024-01-15",
  "quarter": "Q1",
  "year": 2024,
  "is_business_day": true,
  "is_month_end": false
}`,
  },
  balance_fact: {
    id:'balance_fact', label:'Balance Fact', sub:'Daily per account', icon:'\U0001f4b9', layer:'gold', azSvc:'synapse',
    desc:'Core financial fact table in Azure Synapse Dedicated SQL Pool. Daily AUM snapshot per account. Grain: one row per account per day. HASH-distributed on account_key. Includes DQ flags from the reconciliation engine.',
    attrs:['balance_key','account_key','client_key','date_key','market_value','cash','invested','crystallised','uncrystallised','recon_status','dq_score'],
    integration:'ADF incremental load via COPY INTO from ADLS Gen2 Parquet. Staged in Synapse external tables, then inserted into Dedicated SQL Pool. Columnstore index for analytics workloads.',
    freq:'Daily', vol:'~40k rows/day \xb7 ~14M rows/year',
    eg:`{
  "balance_key": 987654,
  "account_key": 20001,
  "client_key": 10001,
  "date_key": 20240115,
  "market_value": 250000.00,
  "crystallised": 150000.00,
  "recon_status": "MATCHED",
  "dq_score": 1.0
}`,
  },
  activity_fact: {
    id:'activity_fact', label:'Activity Fact', sub:'Per event', icon:'\U0001f4ca', layer:'gold', azSvc:'synapse',
    desc:'Adviser activity fact table in Azure Synapse Dedicated SQL Pool. Grain: one row per activity event. HASH-distributed on adviser_key. Used for adviser productivity and FCA activity logging.',
    attrs:['activity_key','client_key','adviser_key','date_key','activity_type','duration_mins','outcome','dq_flag'],
    integration:'ADF full-refresh daily via COPY INTO. Deduplication on activity_id natural key in Synapse staging table before merge into Dedicated SQL Pool.',
    freq:'Daily', vol:'~500 rows/day \xb7 ~180k rows/year',
    eg:`{
  "activity_key": 50001,
  "client_key": 10001,
  "adviser_key": 30001,
  "date_key": 20240115,
  "activity_type": "ANNUAL_REVIEW",
  "duration_mins": 90,
  "outcome": "Completed"
}`,
  },"""

NEW2 = """  client_dim: {
    id:'client_dim', label:'Client Dim', sub:'SCD Type 2', icon:'\U0001f465', layer:'gold', azSvc:'synapsesql',
    desc:'Client dimension with full change history via SCD Type 2. Tracks changes to risk profile, adviser assignment, and business unit over time. One surrogate key per version. Current version flagged with is_current.',
    attrs:['client_key (surrogate)','client_id (business key)','full_name','risk_profile','business_unit','adviser_key','valid_from','valid_to','is_current'],
    integration:'ADF pipeline runs SCD Type 2 merge into Synapse Dedicated SQL Pool. New rows inserted on any attribute change (risk profile, adviser, business unit). Previous version marked is_current = 0, valid_to updated. Surrogate key generated by Synapse IDENTITY column. REPLICATE distribution for dimension table.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool)',
    details:[{title:'Distribution',text:'REPLICATE (small dimension table, copied to all compute nodes)'}],
    eg:`{
  "client_key": 10001,
  "client_id": "C12345",
  "full_name": "Adrian Smith",
  "risk_profile": "BALANCED",
  "business_unit": "RB",
  "adviser_key": 30001,
  "valid_from": "2023-06-01",
  "valid_to": "9999-12-31",
  "is_current": true
}`,
  },
  account_dim: {
    id:'account_dim', label:'Account Dim', sub:'SCD Type 2', icon:'\U0001f4c1', layer:'gold', azSvc:'synapsesql',
    desc:'Account dimension tracking plan type changes, status transitions, and custodian assignments via SCD Type 2. Full history maintained for regulatory audit requirements.',
    attrs:['account_key (surrogate)','account_id (business key)','client_key','plan_type','status','custodian_number','valid_from','valid_to','is_current'],
    integration:'ADF SCD Type 2 merge into Synapse Dedicated SQL Pool. New version created on plan type change, status transition, or custodian reassignment. REPLICATE distribution for dimension table.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool)',
    details:[{title:'Distribution',text:'REPLICATE (small dimension table, copied to all compute nodes)'}],
    eg:`{
  "account_key": 20001,
  "account_id": "ACC001",
  "plan_type": "ISA",
  "status": "ACTIVE",
  "custodian_number": "CUST99",
  "valid_from": "2022-04-06",
  "valid_to": "9999-12-31",
  "is_current": true
}`,
  },
  adviser_dim: {
    id:'adviser_dim', label:'Adviser Dim', sub:'SCD Type 2', icon:'\U0001f9d1\u200d\U0001f4bc', layer:'gold', azSvc:'synapsesql',
    desc:'Adviser dimension built from Curo adviser master. Tracks business unit moves and role changes via SCD Type 2. Type 1 approach for name changes (overwrite).',
    attrs:['adviser_key (surrogate)','adviser_id (business key)','full_name','business_unit','qualification_level','valid_from','valid_to','is_current'],
    integration:'ADF pipeline merges Silver Client Master adviser references with Curo adviser master table. SCD Type 2 applied for business unit and qualification changes. Loaded into Synapse Dedicated SQL Pool. REPLICATE distribution for dimension table.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool)',
    details:[{title:'Distribution',text:'REPLICATE (small dimension table, copied to all compute nodes)'}],
    eg:`{
  "adviser_key": 30001,
  "adviser_id": "A789",
  "full_name": "James Wilson",
  "business_unit": "RB",
  "qualification_level": "Level 4",
  "valid_from": "2022-01-01",
  "is_current": true
}`,
  },
  time_dim: {
    id:'time_dim', label:'Time Dim', sub:'Date Spine', icon:'\U0001f4c5', layer:'gold', azSvc:'synapsesql',
    desc:'Date spine covering 2010 to 2035. Business day flags, FCA reporting periods, and UK public holiday markers included. Static reference table replicated across all Synapse compute nodes for optimal join performance.',
    attrs:['date_key (surrogate)','date','day_of_week','week','month','quarter','year','is_business_day','is_month_end','fca_period','uk_bank_holiday_flag'],
    integration:'Static table loaded once via COPY INTO from ADLS Gen2 CSV file. REPLICATE distribution ensures every compute node has full copy. Refreshed annually to extend forward dates.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool)',
    details:[{title:'Distribution',text:'REPLICATE (small static table, copied to all compute nodes for fast joins)'}],
    eg:`{
  "date_key": 20240115,
  "date": "2024-01-15",
  "day_of_week": "Monday",
  "quarter": "Q1",
  "year": 2024,
  "is_business_day": true,
  "is_month_end": false,
  "uk_bank_holiday_flag": false
}`,
  },
  balance_fact: {
    id:'balance_fact', label:'Balance Fact', sub:'Daily per account', icon:'\U0001f4b9', layer:'gold', azSvc:'synapsesql',
    desc:'Core financial fact table storing daily AUM snapshot per account. Atomic grain: one row per account per date. HASH-distributed on account_key for parallel query performance. Includes DQ flags from Validation & Reconciliation engine. Columnstore index for analytics workloads.',
    attrs:['balance_key (surrogate)','account_key','client_key','date_key','market_value','cash_balance','invested_balance','crystallised (SIPP only)','uncrystallised (SIPP only)','dq_flag','dq_severity'],
    integration:'ADF incremental load via COPY INTO from ADLS Gen2 Parquet (Silver Balance Data). Staged in Synapse external tables, then INSERT into Dedicated SQL Pool fact table. Columnstore clustered index applied. HASH distribution on account_key spreads data evenly across 60 compute nodes.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool), ADLS Gen2',
    details:[
      {title:'Grain',text:'One row per account per date (daily snapshot)'},
      {title:'Distribution',text:'HASH (account_key) - distributes rows evenly across compute nodes for large fact table'},
      {title:'Volume',text:'Approximately 9 million rows per year (25k accounts x 365 days)'},
    ],
    eg:`{
  "balance_key": 987654,
  "account_key": 20001,
  "client_key": 10001,
  "date_key": 20240115,
  "market_value": 250000.00,
  "cash_balance": 5000.00,
  "crystallised": 150000.00,
  "uncrystallised": 100000.00,
  "dq_flag": "PASSED",
  "dq_severity": null
}`,
  },
  activity_fact: {
    id:'activity_fact', label:'Activity Fact', sub:'Per event', icon:'\U0001f4ca', layer:'gold', azSvc:'synapsesql',
    desc:'Adviser activity fact table for productivity tracking and FCA activity logging. Atomic grain: one row per activity event. HASH-distributed on adviser_key. Includes activity type, duration, outcome, and DQ flags.',
    attrs:['activity_key (surrogate)','client_key','adviser_key','date_key','activity_type','duration_mins','outcome','dq_flag'],
    integration:'ADF daily load via COPY INTO from ADLS Gen2 Parquet (Silver Activity Data). Deduplication on activity_id natural key in staging table before INSERT into Dedicated SQL Pool. Columnstore clustered index applied. HASH distribution on adviser_key.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool), ADLS Gen2',
    details:[
      {title:'Grain',text:'One row per activity event'},
      {title:'Distribution',text:'HASH (adviser_key) - distributes rows evenly across compute nodes'},
      {title:'Volume',text:'Approximately 365k rows per year (1000 activities per day)'},
    ],
    eg:`{
  "activity_key": 50001,
  "client_key": 10001,
  "adviser_key": 30001,
  "date_key": 20240115,
  "activity_type": "ANNUAL_REVIEW",
  "duration_mins": 90,
  "outcome": "Completed",
  "dq_flag": "PASSED"
}`,
  },"""

html = apply_change("Change 2: Replace 6 Gold nodes", OLD2, NEW2, html)

# ── Change 3: Insert DataMart nodes before `  abi_wabi: {` ────────────────────
DATAMART_NODES = """  // \u2500\u2500 Data Marts \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  aum_mart: {
    id:'aum_mart', label:'AUM Data Mart', sub:'Daily Aggregates', icon:'\U0001f4b0', layer:'datamart', azSvc:'synapsesql',
    desc:'Pre-aggregated AUM metrics for business unit and adviser reporting. Daily AUM totals by business unit, adviser, client segment, and plan type. Optimised for Power BI DirectQuery performance. REPLICATE distribution for fast queries.',
    attrs:['date_key','business_unit','adviser_id','client_segment','plan_type','total_aum','client_count','avg_account_size','cash_pct','crystallised_pct'],
    integration:'ADF triggers Synapse SQL stored procedure to aggregate Balance Fact daily. Groups by business unit, adviser, client segment, plan type. Results written to Synapse SQL table with columnstore index. REPLICATE distribution ensures fast Power BI queries.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool)',
    details:[
      {title:'Grain',text:'One row per date per business unit per adviser'},
      {title:'Distribution',text:'REPLICATE (pre-aggregated, small result set - copied to all compute nodes for fast queries)'},
      {title:'Measures',items:['Total AUM (sum of market values)','Client count (distinct accounts)','Average account size','Cash percentage','Crystallised percentage (SIPPs only)']},
    ],
    eg:`{
  "date_key": 20240115,
  "business_unit": "RB",
  "adviser_id": "A789",
  "plan_type": "ISA",
  "total_aum": 45000000,
  "client_count": 180,
  "avg_account_size": 250000,
  "cash_pct": 2.0,
  "crystallised_pct": 60.0
}`,
  },
  activity_mart: {
    id:'activity_mart', label:'Activity Data Mart', sub:'Monthly Aggregates', icon:'\U0001f4c5', layer:'datamart', azSvc:'synapsesql',
    desc:'Pre-aggregated adviser productivity metrics. Monthly activity counts, average durations, and completion rates by adviser and activity type. Supports ABI/WABI productivity dashboards.',
    attrs:['month_key','adviser_id','activity_type','activity_count','avg_duration_mins','completion_rate','distinct_clients'],
    integration:'ADF triggers Synapse SQL stored procedure to aggregate Activity Fact monthly. Groups by adviser, activity type. Results written to Synapse SQL table with columnstore index. REPLICATE distribution.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool)',
    details:[
      {title:'Grain',text:'One row per month per adviser per activity type'},
      {title:'Distribution',text:'REPLICATE (pre-aggregated, small result set - copied to all compute nodes)'},
      {title:'Measures',items:['Activity count','Average duration (minutes)','Completion rate (percentage)','Distinct clients engaged']},
    ],
    eg:`{
  "month_key": 202401,
  "adviser_id": "A789",
  "activity_type": "ANNUAL_REVIEW",
  "activity_count": 12,
  "avg_duration_mins": 88,
  "completion_rate": 91.7,
  "distinct_clients": 12
}`,
  },
  client360_mart: {
    id:'client360_mart', label:'Client 360 Data Mart', sub:'Denormalised', icon:'\U0001f464', layer:'datamart', azSvc:'synapsesql',
    desc:'Denormalised client view combining client attributes, account summary, and activity history. Optimised for client analytics and segmentation. One row per client with aggregated account and activity metrics.',
    attrs:['client_id','full_name','risk_profile','business_unit','adviser_id','total_aum','account_count','plan_types_held','last_review_date','reviews_ytd','recommendations_ytd'],
    integration:'ADF triggers Synapse SQL stored procedure to join Client Dimension with aggregated Balance Fact and Activity Fact metrics. Results written to Synapse SQL table with HASH distribution on client_id.\\n\\nAzure Services: Data Factory, Synapse Analytics (Dedicated SQL Pool)',
    details:[
      {title:'Grain',text:'One row per client (denormalised)'},
      {title:'Distribution',text:'HASH (client_id) - distributes rows across compute nodes'},
      {title:'Attributes',items:['Client attributes (name, risk profile, business unit, adviser)','Account summary (total AUM, account count, plan types held)','Activity summary (last review date, reviews year-to-date, recommendations year-to-date)']},
    ],
    eg:`{
  "client_id": "C12345",
  "full_name": "Adrian Smith",
  "risk_profile": "BALANCED",
  "total_aum": 250000,
  "account_count": 3,
  "last_review_date": "2024-01-15",
  "reviews_ytd": 1
}`,
  },

  // \u2500\u2500 Semantic Layer \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  glossary: {
    id:'glossary', label:'Business Glossary', sub:'Semantic Layer', icon:'\U0001f4d6', layer:'datamart',
    desc:'Centralised business definitions, metric calculations, and term standardisation. Defines "AUM", "Client Count", "Adviser Productivity" with precise calculation logic. Accessible to BI users, analysts, and AI tools for consistent understanding.',
    details:[
      {title:'Contents',items:['Metric definitions (e.g. AUM = SUM of market_value WHERE status = Active)','Business term glossary (e.g. ISA = Individual Savings Account, \xa320k annual limit)','Calculation rules (e.g. Crystallised % = crystallised / total_value * 100)','Data ownership (e.g. AUM metrics owned by Finance team)']},
      {title:'Technology',text:'Azure Purview Data Catalog OR custom metadata database OR Power BI datasets with DAX measures documentation'},
    ],
    integration:'Business analysts define terms. Data team publishes to catalog. BI tools and AI query engines reference for context.',
  },
  lineage: {
    id:'lineage', label:'Lineage', sub:'Semantic Layer', icon:'\U0001f517', layer:'datamart',
    desc:'End-to-end data lineage from source systems through Bronze, Silver, Gold to Data Marts and consumption. Tracks transformations, dependencies, and impact analysis. Enables "where did this number come from?" questions.',
    details:[
      {title:'Examples',items:['"AUM Data Mart.total_aum" aggregated from "Balance Fact.market_value" joined from "Silver Balance Data" merged from "Bronze Mabel + Bronze BW"','"Activity Data Mart.completion_rate" calculated from "Activity Fact.outcome" sourced from "Silver Activity Data" sourced from "Bronze HubWise"']},
      {title:'Technology',text:'Azure Purview OR dbt lineage graphs OR custom lineage tracking in metadata database'},
    ],
    integration:'Automated lineage capture from ADF pipelines, Synapse SQL queries, and Power BI dataset refresh logs.',
  },
  dq_metrics: {
    id:'dq_metrics', label:'DQ Metrics', sub:'Semantic Layer', icon:'\U0001f4ca', layer:'datamart', azSvc:'pbi',
    desc:'Aggregated data quality scores and trends. Tracks completeness, accuracy, timeliness, and consistency across all layers. Published to BI dashboards for data stewards and business users.',
    details:[
      {title:'Metrics',items:['Completeness scores by source system (e.g. Curo client records 99.8% complete)','DQ issue trends (e.g. Mabel orphan accounts decreased from 50 to 12 this month)','Timeliness SLA tracking (e.g. Bronze ingestion completed by 07:00 95% of days)','Critical issue alerts (e.g. 15 CRITICAL severity DQ flags in last 7 days)']},
      {title:'Technology',text:'Data Quality dashboard in Power BI querying DQ metadata table from Bronze V&R and Silver processing'},
    ],
    integration:'ADF pipelines log DQ metrics to Azure SQL metadata table. Power BI refreshes hourly.',
  },
  business_rules: {
    id:'business_rules', label:'Business Rules', sub:'Semantic Layer', icon:'\U0001f4dc', layer:'datamart',
    desc:'Codified business logic and regulatory rules applied in transformations. Documents ISA limits, pension crystallisation rules, risk profile classifications, and FCA compliance requirements.',
    details:[
      {title:'Examples',items:['"ISA Annual Limit: \xa320,000 per tax year (April to April)"','"SIPP Crystallisation: Age 55+ can crystallise up to 25% tax-free"','"Risk Profile Categories: Conservative (1-3), Balanced (4-6), Growth (7-10)"','"FCA Review Frequency: Minimum annual review for advised clients"']},
      {title:'Technology',text:'Documented in Azure Purview OR dbt project documentation OR custom business rules repository'},
    ],
    integration:'Referenced in Silver/Gold transformation logic. Validated in DQ checks.',
  },

  // \u2500\u2500 Security & Governance \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  rls: {
    id:'rls', label:'Row-Level Security', sub:'Security & Governance', icon:'\U0001f510', layer:'datamart', azSvc:'pbi',
    desc:'Filters data based on user identity and business unit. Internal advisers see all clients. SPP (Saltus Partnership Programme) external advisers see only clients in their business unit. Clients see only their own accounts.',
    details:[
      {title:'Implementation',items:['Power BI RLS roles (Adviser, SPP Partner, Client)','Synapse SQL views with SECURITY POLICY filtering','Filter predicates: WHERE business_unit = USER_BUSINESS_UNIT() OR IS_INTERNAL_USER()']},
      {title:'Technology',text:'Power BI Row-Level Security + Azure AD groups OR Synapse Dynamic Data Masking + Row-Level Security'},
    ],
    integration:'RLS policies configured in Power BI workspaces and Synapse SQL views. Azure AD group membership determines effective permissions.',
  },
  column_security: {
    id:'column_security', label:'Column Security', sub:'Security & Governance', icon:'\U0001f512', layer:'datamart',
    desc:'Restricts access to sensitive columns based on role. Finance team sees all fields. Operations team sees client_id but not full name, address, or contact details (PII minimisation). Clients see balances but not internal cost/fee calculations.',
    details:[
      {title:'Implementation',items:['Synapse SQL views with selective column exposure','Power BI hidden columns for sensitive fields','Dynamic data masking for PII fields']},
      {title:'Technology',text:'Synapse Dynamic Data Masking + Power BI field-level security'},
    ],
    integration:'Column restrictions enforced at Synapse SQL view layer. Power BI field-level permissions configured per workspace role.',
  },
  audit_logs: {
    id:'audit_logs', label:'Access Audit Logs', sub:'Security & Governance', icon:'\U0001f4cb', layer:'datamart',
    desc:'Comprehensive logging of all data access. Tracks who queried what data when. Supports FCA audit requirements and incident investigation. Logs retained for 7 years.',
    details:[
      {title:'Logged Events',items:['Power BI report views (user, report, timestamp)','Synapse SQL queries (user, tables accessed, row count returned)','Data Mart refreshes (pipeline, success/failure, duration)','DQ alert triggers (severity, source, resolution)']},
      {title:'Technology',text:'Azure Monitor + Log Analytics workspace querying ADF pipeline logs, Synapse query logs, Power BI activity logs'},
    ],
    integration:'All platform components emit logs to Azure Monitor. Log Analytics workspace aggregates and indexes for querying. Retained 7 years for FCA compliance.',
  },
  rbac: {
    id:'rbac', label:'RBAC Enforcement', sub:'Security & Governance', icon:'\U0001f465', layer:'datamart',
    desc:'Role-Based Access Control across all platform components. Roles defined: Data Engineer, Data Analyst, Business User, Finance User, Compliance User, Client. Permissions enforced at Azure resource level, Synapse database level, and Power BI workspace level.',
    details:[
      {title:'Roles & Permissions',items:['Data Engineer: Full ADLS Gen2 + Synapse access (read/write all layers)','Data Analyst: Read access to Silver/Gold/Data Marts, write access to Power BI','Business User: Power BI consumption only (no direct database access)','Finance User: Power BI + direct query to Finance-specific Data Marts','Compliance User: Read-only access to DQ metadata and audit logs','Client: Power BI embedded reports with RLS filtering to own accounts only']},
      {title:'Technology',text:'Azure RBAC + Azure AD groups + Synapse database roles + Power BI workspace roles'},
    ],
    integration:'Azure AD groups mapped to RBAC roles. Synapse database role assignments aligned with AD groups. Power BI workspace roles match RBAC definitions.',
  },

"""

OLD3 = "  abi_wabi: {"
NEW3 = DATAMART_NODES + "  abi_wabi: {"
html = apply_change("Change 3: Insert DataMart nodes before abi_wabi", OLD3, NEW3, html)

# ── Change 4: Update CONNS Gold→Consumer section ──────────────────────────────
OLD4 = "  // Gold \u2192 Consumers\n  {f:'client_dim',t:'abi_wabi',lbl:'Power BI DirectQuery'},{f:'account_dim',t:'abi_wabi',lbl:'Power BI DirectQuery'},{f:'adviser_dim',t:'abi_wabi',lbl:'Power BI DirectQuery'},{f:'time_dim',t:'abi_wabi',lbl:'Power BI DirectQuery'},{f:'balance_fact',t:'abi_wabi',lbl:'Power BI DirectQuery'},{f:'activity_fact',t:'abi_wabi',lbl:'Power BI DirectQuery'},{f:'client_dim',t:'fbi',lbl:'Power BI DirectQuery'},{f:'account_dim',t:'fbi',lbl:'Power BI DirectQuery'},{f:'time_dim',t:'fbi',lbl:'Power BI DirectQuery'},{f:'balance_fact',t:'fbi',lbl:'Power BI DirectQuery'},{f:'client_dim',t:'portal',lbl:'APIM to Synapse Serverless'},{f:'account_dim',t:'portal',lbl:'APIM to Synapse Serverless'},{f:'time_dim',t:'portal',lbl:'APIM to Synapse Serverless'},{f:'balance_fact',t:'portal',lbl:'APIM to Synapse Serverless'},"
NEW4 = "  // Gold \u2192 Data Marts\n  {f:'balance_fact',t:'aum_mart',lbl:'ADF aggregates Balance Fact into AUM Data Mart daily'},{f:'activity_fact',t:'activity_mart',lbl:'ADF aggregates Activity Fact into Activity Data Mart monthly'},{f:'client_dim',t:'client360_mart',lbl:'ADF joins Client Dimension into Client 360 Data Mart'},{f:'balance_fact',t:'client360_mart',lbl:'ADF aggregates Balance Fact into Client 360 Data Mart'},{f:'activity_fact',t:'client360_mart',lbl:'ADF aggregates Activity Fact into Client 360 Data Mart'},\n  // Data Marts \u2192 Power BI Consumers\n  {f:'aum_mart',t:'abi_wabi',lbl:'Power BI DirectQuery to AUM Data Mart'},{f:'activity_mart',t:'abi_wabi',lbl:'Power BI DirectQuery to Activity Data Mart'},{f:'client360_mart',t:'abi_wabi',lbl:'Power BI DirectQuery to Client 360 Data Mart'},{f:'aum_mart',t:'fbi',lbl:'Power BI DirectQuery to AUM Data Mart'},{f:'client360_mart',t:'fbi',lbl:'Power BI DirectQuery to Client 360 Data Mart'},\n  // Gold \u2192 Portal (direct real-time API queries)\n  {f:'client_dim',t:'portal',lbl:'APIM to Synapse Serverless'},{f:'account_dim',t:'portal',lbl:'APIM to Synapse Serverless'},{f:'time_dim',t:'portal',lbl:'APIM to Synapse Serverless'},{f:'balance_fact',t:'portal',lbl:'APIM to Synapse Serverless'},"
html = apply_change("Change 4: Update CONNS Gold->Consumer section", OLD4, NEW4, html)

# ── Change 5: Update LAYERS ───────────────────────────────────────────────────
OLD5 = "  {key:'gold',     label:'GOLD: Synapse Dedicated SQL Pool', rows:[['client_dim','account_dim','adviser_dim','time_dim','balance_fact','activity_fact']]},\n  {key:'consumer', label:'CONSUMERS',                         rows:[['abi_wabi','fbi','portal']]},"
NEW5 = "  {key:'gold',     label:'GOLD: Synapse Dedicated SQL Pool', rows:[['client_dim','account_dim','adviser_dim','time_dim','balance_fact','activity_fact']]},\n  {key:'datamart', label:'DATA MARTS + SEMANTIC LAYER',      rows:[['aum_mart','activity_mart','client360_mart'],['glossary','lineage','dq_metrics','business_rules'],['rls','column_security','audit_logs','rbac']], rowLabels:['Data Marts','Semantic Layer','Security & Governance']},\n  {key:'consumer', label:'CONSUMERS',                         rows:[['abi_wabi','fbi','portal']]},"
html = apply_change("Change 5: Update LAYERS", OLD5, NEW5, html)

# ── Change 6: Update legend strip ─────────────────────────────────────────────
OLD6 = "[['#3b82f6','Sources'],['#f59e0b','Bronze'],['#94a3b8','Silver'],['#eab308','Gold'],['#22c55e','Consumers']]"
NEW6 = "[['#3b82f6','Sources'],['#f59e0b','Bronze'],['#94a3b8','Silver'],['#eab308','Gold'],['#8b5cf6','Data Marts'],['#22c55e','Consumers']]"
html = apply_change("Change 6: Update legend strip", OLD6, NEW6, html)

# ── Change 7a: Update layer renderer to support rowLabels ─────────────────────
OLD7A = """                    {layer.rows.map((rowIds, ri) => (
                      <div key={ri} style={{
                        display:'flex', justifyContent:'center', gap:14, flexWrap:'wrap',
                        marginBottom: ri < layer.rows.length - 1 ? 18 : 0,
                      }}>"""
NEW7A = """                    {layer.rows.map((rowIds, ri) => (
                      <div key={ri} style={{marginBottom: ri < layer.rows.length - 1 ? 22 : 0}}>
                        {layer.rowLabels && layer.rowLabels[ri] && (
                          <div style={{
                            fontSize:8, fontWeight:700, textTransform:'uppercase', letterSpacing:2,
                            color:`${LC[layer.key]}99`, marginBottom:8, textAlign:'center',
                            borderBottom:`1px solid ${LC[layer.key]}22`, paddingBottom:6,
                          }}>{layer.rowLabels[ri]}</div>
                        )}
                      <div style={{
                        display:'flex', justifyContent:'center', gap:14, flexWrap:'wrap',
                      }}>"""
html = apply_change("Change 7a: Update layer renderer rowLabels opening", OLD7A, NEW7A, html)

# ── Change 7b: Close the extra wrapping div ───────────────────────────────────
# Find the FIRST occurrence of the closing divs after the layer renderer
OLD7B = """                      </div>
                    ))}"""
NEW7B = """                      </div>
                      </div>
                    ))}"""
html = apply_change("Change 7b: Add extra closing div for rowLabels wrapper", OLD7B, NEW7B, html)

# ── Change 8a: Make attrs optional in DetailPanel ────────────────────────────
OLD8A = """      <Sec title="Attributes & Fields">
        <div style={{display:'flex', flexWrap:'wrap', gap:4}}>
          {node.attrs.map(a => (
            <span key={a} style={{
              background:'rgba(0,120,212,0.12)', border:'1px solid rgba(0,120,212,0.25)',
              borderRadius:4, padding:'2px 8px', fontSize:10.5, fontFamily:'monospace',
              color:'rgba(220,232,245,0.85)',
            }}>{a}</span>
          ))}
        </div>
      </Sec>"""
NEW8A = """      {node.attrs && node.attrs.length > 0 && (
        <Sec title="Attributes & Fields">
          <div style={{display:'flex', flexWrap:'wrap', gap:4}}>
            {node.attrs.map(a => (
              <span key={a} style={{
                background:'rgba(0,120,212,0.12)', border:'1px solid rgba(0,120,212,0.25)',
                borderRadius:4, padding:'2px 8px', fontSize:10.5, fontFamily:'monospace',
                color:'rgba(220,232,245,0.85)',
              }}>{a}</span>
            ))}
          </div>
        </Sec>
      )}"""
html = apply_change("Change 8a: Make attrs optional in DetailPanel", OLD8A, NEW8A, html)

# ── Change 8b: Add details rendering and make eg optional ────────────────────
OLD8B = """      <Sec title="Example Payload">
        <pre style={{
          background:'#030c14', borderRadius:8, padding:14,
          fontFamily:"'Courier New',monospace", fontSize:11, color:'#7dd3f8',
          border:'1px solid rgba(0,120,212,0.15)',
          overflowX:'auto', whiteSpace:'pre', lineHeight:1.65, margin:0,
        }}>{node.eg}</pre>
      </Sec>"""
NEW8B = """      {node.details && node.details.map(({title,text,items},di) => (
        <Sec key={di} title={title}>
          {text
            ? <p style={{fontSize:12.5, lineHeight:1.8, color:'rgba(220,232,245,0.82)', fontWeight:400}}>{text}</p>
            : <ul style={{margin:0, paddingLeft:16, listStyle:'disc'}}>
                {items.map((item,ii) => <li key={ii} style={{fontSize:12.5, lineHeight:1.8, color:'rgba(220,232,245,0.82)', fontWeight:400, marginBottom:2}}>{item}</li>)}
              </ul>
          }
        </Sec>
      ))}

      {node.eg && (
        <Sec title="Example Payload">
          <pre style={{
            background:'#030c14', borderRadius:8, padding:14,
            fontFamily:"'Courier New',monospace", fontSize:11, color:'#7dd3f8',
            border:'1px solid rgba(0,120,212,0.15)',
            overflowX:'auto', whiteSpace:'pre', lineHeight:1.65, margin:0,
          }}>{node.eg}</pre>
        </Sec>
      )}"""
html = apply_change("Change 8b: Add details rendering and make eg optional", OLD8B, NEW8B, html)

# ── Write final file ──────────────────────────────────────────────────────────
with open(FILE, 'w', encoding='utf-8') as f:
    f.write(html)

line_count = html.count('\n') + 1
print(f"\nFile written. Total line count: {line_count}")
print(f"Changes applied: {changes_ok} / {changes_ok + changes_fail}")
if changes_fail > 0:
    print(f"WARNING: {changes_fail} change(s) FAILED")
    sys.exit(1)
else:
    print("All changes applied successfully.")
